### ISSUE TITLE
problem files do not have f90 extension

### ISSUE THREAD

**Issue by dpo** [ralna/CUTEst#12]
[Line 434 of runcutest](https://github.com/ralna/CUTEst/blob/master/bin/runcutest#L434) tries to compile the problem files with an `f90` extension. Is that intentional? That causes an error for me on macOS. I wonder how anyone has been able to use `runcutest`?! Those files have extension `f`. This fixes it for me:
```diff
434c434
<         command="${FORTRAN} ${PROBFLAGS} ${i}.f90"
---
>         command="${FORTRAN} ${PROBFLAGS} ${i}.f"
```

**Comment by nimgould** [comment]
The line before (433) copies the .f files to .f90 ones. This is
simply so that older compilers (e.g. xlf) that don't distinguish 77 from 90
format don't have to add an explicit compiler flag to specify
that the old source form is in use. I don't understand why your
problem files weren't copied according to the 433 rule,
        ${CP} ${i}.f ${i}.f90

**Comment by dpo** [comment]
Oh sorry, I missed that. I guess it didn't happen because there already exist problem `.o` files in the current directory. I suppose this is the user's fault and I should have used `-r` to recompile problem files?! Anyways, now I'm not able to reproduce the failure anymore. Sorry for the noise.
