### ISSUE TITLE
Errors during the compilation

### ISSUE THREAD

**Issue by amontoison** [ralna/CUTEst#37]
```
[1/2] Compiling Fortran object libcutest.so.p/src_tools_readin.f90.o
FAILED: libcutest.so.p/src_tools_readin.f90.o libcutest.so.p/read_input.mod 
gfortran -Ilibcutest.so.p -I. -I.. -I../include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -O3 -fPIC -Jlibcutest.so.p -o libcutest.so.p/src_tools_readin.f90.o -c ../src/tools/readin.f90
../src/tools/readin.f90:25:25:

   25 |          REAL ( KIND = wp ), PARAMETER, PRIVATE :: zero = 0.0_wp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:33:25:

   33 |          REAL ( KIND = wp ), INTENT( IN ) :: rdefault
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:34:25:

   34 |          REAL ( KIND = wp ), INTENT( INOUT ) :: r
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:35:25:

   35 |          REAL ( KIND = wp ) :: rtemp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:74:25:

   74 |          REAL ( KIND = wp ), INTENT( INOUT ) :: r
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:75:25:

   75 |          REAL ( KIND = wp ) :: rtemp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:72:35:

   72 |          SUBROUTINE OVERIDE_real( r, unit )
      |                                   1
Error: Symbol ‘r’ at (1) has no IMPLICIT type
../src/tools/readin.f90:31:32:

   31 |          SUBROUTINE READ_real( r, rdefault, unit )
      |                                1
Error: Symbol ‘r’ at (1) has no IMPLICIT type
../src/tools/readin.f90:31:42:

   31 |          SUBROUTINE READ_real( r, rdefault, unit )
      |                                          1
Error: Symbol ‘rdefault’ at (1) has no IMPLICIT type
../src/tools/readin.f90:76:41:

   76 |          READ( unit, "( ES10.3 )" ) rtemp
      |                                         1
Error: Symbol ‘rtemp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:77:27:

   77 |          IF ( rtemp >= zero ) r = rtemp
      |                           1
Error: Symbol ‘zero’ at (1) has no IMPLICIT type
../src/tools/readin.f90:36:33:

   36 |          READ( unit, 1000 ) rtemp
      |                                 1
Error: Symbol ‘rtemp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:37:27:

   37 |          IF ( rtemp >= zero ) THEN
      |                           1
Error: Symbol ‘zero’ at (1) has no IMPLICIT type
ninja: build stopped: subcommand failed.
```

**Comment by nimgould** [comment]
This will because the sed script will activate the wp variable

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Alexis Montoison ***@***.***>
Sent: Sunday, October 22, 2023 8:24:19 AM
To: ralna/CUTEst ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ralna/CUTEst] Errors during the compilation (Issue #37)


[1/2] Compiling Fortran object libcutest.so.p/src_tools_readin.f90.o
FAILED: libcutest.so.p/src_tools_readin.f90.o libcutest.so.p/read_input.mod
gfortran -Ilibcutest.so.p -I. -I.. -I../include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -O3 -fPIC -Jlibcutest.so.p -o libcutest.so.p/src_tools_readin.f90.o -c ../src/tools/readin.f90
../src/tools/readin.f90:25:25:

   25 |          REAL ( KIND = wp ), PARAMETER, PRIVATE :: zero = 0.0_wp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:33:25:

   33 |          REAL ( KIND = wp ), INTENT( IN ) :: rdefault
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:34:25:

   34 |          REAL ( KIND = wp ), INTENT( INOUT ) :: r
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:35:25:

   35 |          REAL ( KIND = wp ) :: rtemp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:74:25:

   74 |          REAL ( KIND = wp ), INTENT( INOUT ) :: r
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:75:25:

   75 |          REAL ( KIND = wp ) :: rtemp
      |                         1
Error: Symbol ‘wp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:72:35:

   72 |          SUBROUTINE OVERIDE_real( r, unit )
      |                                   1
Error: Symbol ‘r’ at (1) has no IMPLICIT type
../src/tools/readin.f90:31:32:

   31 |          SUBROUTINE READ_real( r, rdefault, unit )
      |                                1
Error: Symbol ‘r’ at (1) has no IMPLICIT type
../src/tools/readin.f90:31:42:

   31 |          SUBROUTINE READ_real( r, rdefault, unit )
      |                                          1
Error: Symbol ‘rdefault’ at (1) has no IMPLICIT type
../src/tools/readin.f90:76:41:

   76 |          READ( unit, "( ES10.3 )" ) rtemp
      |                                         1
Error: Symbol ‘rtemp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:77:27:

   77 |          IF ( rtemp >= zero ) r = rtemp
      |                           1
Error: Symbol ‘zero’ at (1) has no IMPLICIT type
../src/tools/readin.f90:36:33:

   36 |          READ( unit, 1000 ) rtemp
      |                                 1
Error: Symbol ‘rtemp’ at (1) has no IMPLICIT type
../src/tools/readin.f90:37:27:

   37 |          IF ( rtemp >= zero ) THEN
      |                           1
Error: Symbol ‘zero’ at (1) has no IMPLICIT type
ninja: build stopped: subcommand failed.
